### PR TITLE
Backoff

### PR DESCRIPTION
**Pull request by kpashka**
Hi Jonathan!

It's an awesome project idea, I've did something similar recently, but it was way too simpler (without notifications & web UI).

Do you accept contributions?

I've implemented basic backoff interface & several implementations.

### CODE REVIEW

**Comment by jonog** [comment]
Hi Pavel! Nice one, contributions welcome, and looks like a great feature!
Just as a heads up - away for ~a week + few days so might be a bit slow during this time, but should be all good to check this out in the next day.

**Comment by jonog** [comment]
Nice, looks good!
If no backoff is specified, I'm thinking should also have a default interval, e.g. 10 seconds. i.e. Maybe can change config type to a pointer and detect for nil.
Also, re. naming I think inside the backoffs package we could keep the names shorter. i.e. `backoffs.BackoffConfig` -> `backoffs.Config`
Will merge and pickup on these in separate commits.

**Comment by jonog** [comment]
Actually, on second look at Exponential - I think it should actually be calculating the next delay using the last delay. so `next delay = last delay * multiplier`. Another way of expressing this would be (multiplier ^ fail count) * interval. What do you think?

**Comment by jonog** [comment]
https://github.com/jonog/redalert/pull/7/files

**Comment by kpashka** [comment]
Looks good. There is more complex implementations of Exponential Backoff, e.g. here https://github.com/cenkalti/backoff/blob/master/exponential.go#L9

But they can be added later via same interface.

**Pull request merged**
